on: 
  workflow_dispatch:
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Jira Create issue
      run: |
        curl --request POST \
        --url 'https://utsav-garg.atlassian.net/rest/api/3/issue' \
        --user '${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}' \
        --header 'Accept: application/json' \
        --header 'Content-Type: application/json' \
        --data '{
          "fields": {
             "project":
             {
                "id": "10000"
             },
             "customfield_10035": "v1.1.1",
             "summary": "Test Summary.",
             "description": {
                "type": "doc",
                "version": 1,
                "content": [
                  {
                    "type": "paragraph",
                    "content": [
                      {
                        "type": "text",
                        "text": "description"
                      }
                    ]
                  }
                ]
              },
             "issuetype": {
                "id": "10001"
             }
           }
        }'
      
